theme: jekyll-theme-cayman
arxiv_url: https://proceedings.mlr.press/v162/trinh22a.html
title: Tackling covariate shift with node-based Bayesian neural networks
tagline: This website contains information regarding the paper Tackling covariate shift with node-based Bayesian neural networks.