theme: jekyll-theme-cayman
arxiv_url: https://arxiv.org/abs/2206.02435
title: Tackling covariate shift with node-based Bayesian neural networks
tagline: This website contains information regarding the paper Tackling covariate shift with node-based Bayesian neural networks.